### ISSUE TITLE
Is there any way force CE to use a fixed function pipeline, but still use dx8?  (Sorry if this is the wrong place to ask)

### ISSUE THREAD

**Issue by TheGreatHMMMM** [Sledmine/censhine#3]
Supposedly disabling shaders forces CE to run in dx7 and use a fixed function pipeline.  However RTX Remix doesn't have support for dx7 games yet, but CE already uses dx8 when using shaders.  So I was wondering if there was a way to use a fixed function pipeline while in dx8. I'd love to see CE fully path traced.  I'm not sure if this is possible, but I thought it was worth an ask.

Cool project btw...

**Comment by Sledmine** [comment]
I'm not sure, I mean as far as I know Halo has a fixed function mode but it's uknown to me which DirectX version is using while on that mode, I have not too much knowledge about fixed function but Google kinda gave me an idea and it seems like it is not doable if you want to use DX8.

Why is fixed function important for RTX Remix, is that a requirement to use it? (I thought DX9 games were compatible with RTX Remix)

Thank you :3

**Comment by Sledmine** [comment]
Closing due not being a real issue and lack of comments.
