### ISSUE TITLE
Halo CE Refined and this shader

### ISSUE THREAD

**Issue by wof8317** [Sledmine/censhine#4]
Is this supposed to be separate from HCE refined or can it work in companion with this shader? By separate, I mean not compatible with HCE refined.

**Comment by MrChromed** [comment]
> Is this supposed to be separate from HCE refined or can it work in companion with this shader?

It totally works with Halo CE Refined, as CEnshine is a mod that replaces a specific shader file that is responsible for the rendering of the whole game in terms of Pixel and Vertex shadering.

**Comment by wof8317** [comment]
Well that was quick. Thanks for the reply.

**Comment by Sledmine** [comment]
Closing as comment got resolved.
