### ISSUE TITLE
How do you install it for halo Combat Evolved (not custom edition)?

### ISSUE THREAD

**Issue by Rockship2910** [Sledmine/censhine#5]

**Comment by MrChromed** [comment]
Unfortunately you can't. Currently CEnshine is only compatible with Custom Edition. We're considering doing a Halo Retail version of CEnshine, but due to priorities in our other projects/mods, we can't deliver an ETA.

**Comment by Rockship2910** [comment]
Oh ok I will close when you guys have it. And that was a FAST reply
