### ISSUE TITLE
New Intel ARC D3D9 driver and water flickering

### ISSUE THREAD

**Issue by donizettilorenzo** [Sledmine/censhine#7]
Water seems to have some Z-fighting/texture mapping (?) issue with the last Intel ARC D3D9 driver (now that they provide a real driver and not a d3d9to12 wrapper), no problem with original shader package.

![0](https://github.com/Sledmine/censhine/assets/1938669/7e87bb34-13d0-494e-8b19-578298e9ffcb)
![1](https://github.com/Sledmine/censhine/assets/1938669/cce6bc71-5d36-485f-8b0a-5f7d7d80603b)
![2](https://github.com/Sledmine/censhine/assets/1938669/29d56284-d113-4601-aca0-a6f656bffb2a)

**Comment by Sledmine** [comment]
I do not have that hardware to test why that is happening, however I would say it must be an issue with the driver or the hardware itself, shaders must be 100% compatible DirectX9 Bytecode, if it is not working on Intel ARC GPUs I would blame them...

I'll keep it in mind! but I cant promise I would be able to fix that.
